remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

title: Test of github page
description: Some tests
show_downloads: true

github:
  zip_url: https://github.com/Shadow15510/test-page/archive/refs/heads/master.zip
  readthedocs: http://irc-api.rtfd.io/
