remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Page test
description:
show_downloads: false

github:
  readthedocs: http://irc-api.rtfd.io/
